name: Deploy to Development

on:
  push:
    branches: [ "development" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    env:
      SSH_KEY: ${{secrets.SSH_KEY}}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install
    - run: npm run build:dev
    - run: sh ${GITHUB_WORKSPACE}/scripts/deploy.sh $SSH_KEY dev
